package handlers

var expectedColumnsInCsv = []string{
	"time_iso", "time_unix", "electric_power_demand",
	"gnss_altitude", "gnss_course", "gnss_latitude", "gnss_longitude",
	"itcs_bus_route", "itcs_number_of_passengers", "itcs_stop_name",
	"odometry_articulation_angle", "odometry_steering_angle", "odometry_vehicle_speed",
	"odometry_wheel_speed_fl", "odometry_wheel_speed_fr", "odometry_wheel_speed_ml",
	"odometry_wheel_speed_mr", "odometry_wheel_speed_rl", "odometry_wheel_speed_rr",
	"status_door_is_open", "status_grid_is_available", "status_halt_brake_is_active", "status_park_brake_is_active",
	"temperature_ambient", "traction_brake_pressure", "traction_traction_force",
}

var csvHeaderToDb = map[string]string{
	"time_iso":                   "time_iso",
	"time_unix":                  "time_unix",
	"electric_powerDemand":       "electric_power_demand",
	"gnss_altitude":              "gnss_altitude",
	"gnss_course":                "gnss_course",
	"gnss_latitude":              "gnss_latitude",
	"gnss_longitude":             "gnss_longitude",
	"itcs_busRoute":              "itcs_bus_route",
	"itcs_numberOfPassengers":    "itcs_number_of_passengers",
	"itcs_stopName":              "itcs_stop_name",
	"odometry_articulationAngle": "odometry_articulation_angle",
	"odometry_steeringAngle":     "odometry_steering_angle",
	"odometry_vehicleSpeed":      "odometry_vehicle_speed",
	"odometry_wheelSpeed_fl":     "odometry_wheel_speed_fl",
	"odometry_wheelSpeed_fr":     "odometry_wheel_speed_fr",
	"odometry_wheelSpeed_ml":     "odometry_wheel_speed_ml",
	"odometry_wheelSpeed_mr":     "odometry_wheel_speed_mr",
	"odometry_wheelSpeed_rl":     "odometry_wheel_speed_rl",
	"odometry_wheelSpeed_rr":     "odometry_wheel_speed_rr",
	"status_doorIsOpen":          "status_door_is_open",
	"status_gridIsAvailable":     "status_grid_is_available",
	"status_haltBrakeIsActive":   "status_halt_brake_is_active",
	"status_parkBrakeIsActive":   "status_park_brake_is_active",
	"temperature_ambient":        "temperature_ambient",
	"traction_brakePressure":     "traction_brake_pressure",
	"traction_tractionForce":     "traction_traction_force",
}
